apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: dokuwiki
      kind: HelmChart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: dokuwiki
        version: "11.1.6"
    - name: additional-files
      path: artifacts
      kind: Kustomize
